### ISSUE TITLE
Move proposal to WICG

### ISSUE THREAD

**Issue by igrigorik** [mounirlamouri/memory-pressure-api#2]
It would be great if we could move this proposal to WICG to get wider review + input from other vendors. Notes from TPAC: https://github.com/w3c/charter-webperf/issues/33

/cc @yoavweiss @cwilso @marcoscaceres ... another one :-)

**Comment by yoavweiss** [comment]
This proposal seen a lot of interest both from browser vendors as well as perf-oriented developers (it was discussed at a Velocity meetup back in June)

At the same time, I don't think it has a discourse thread gathering wider community feedback.

@cwilso & @marcoscaceres - WDYT? Should a discourse thread be a requirement for moving repos over?

**Comment by marcoscaceres** [comment]
I think it's good to have a thread just announcing the the work is spinning up based on the above - and a description of the use cases to get people who were not part of the initial discussions interested.

**Comment by igrigorik** [comment]
@mounirlamouri do you want to kick one off on https://discourse.wicg.io? Alternatively, I can post a quick summary early next week.

**Comment by mounirlamouri** [comment]
As discussed in another email thread, I will do this @igrigorik.

**Comment by mounirlamouri** [comment]
@marcoscaceres https://discourse.wicg.io/t/proposal-memory-pressure-api/1746

**Comment by marcoscaceres** [comment]
As this was moved to the WICG, closing this issue.
